/**
 * Seed script: populates ingredientes_catalogo, platos_catalogo, and plato_ingredientes
 * from the RECETARIO SELECTA data.
 *
 * Prerequisites:
 *   1. Run the SQL migration (Step 1) in Supabase SQL Editor first.
 *   2. npm install (ensure @supabase/supabase-js is available)
 *
 * Usage:
 *   npx ts-node scripts/seed-recetario.ts
 */

import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://xvvbxyjcieckbbdcuoge.supabase.co";
const SUPABASE_SERVICE_ROLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2dmJ4eWpjaWVja2JiZGN1b2dlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTYzNjg3NywiZXhwIjoyMDY3MjEyODc3fQ.D9ZxxX9PU4788j9OGNwfqbUmFqACEXT4C6bJgaKUDYs";

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

// ─── Ingredient definition: [nombre, unidad, proveedor?] ───
// We collect unique ingredients. The key is `nombre` (lowercase-normalized).
interface IngDef {
  nombre: string;
  unidad: string;
  proveedor: string | null;
}

interface DishDef {
  nombre: string;
  categoria: string;
  porciones_receta: number | null;
  tiempo_preparacion: string | null;
  temperatura_coccion: string | null;
  rendimiento: string | null;
  notas: string | null;
  ingredientes: Array<{ nombre: string; cantidad: number; unidad: string }>;
}

// ─── ALL UNIQUE INGREDIENTS ───
const allIngredients: IngDef[] = [
  // Waters/Liquids
  { nombre: "Agua", unidad: "ml", proveedor: null },
  { nombre: "Hielo", unidad: "gr", proveedor: "Iglu" },
  // Sugars/Sweeteners
  { nombre: "Panela", unidad: "gr", proveedor: null },
  { nombre: "Azúcar", unidad: "gr", proveedor: "Incauca" },
  { nombre: "Miel de Maple", unidad: "ml", proveedor: "Syrup" },
  { nombre: "Dulce Quemado", unidad: "ml", proveedor: "A Voelkl" },
  // Spices/Seasonings
  { nombre: "Clavos de Olor", unidad: "gr", proveedor: null },
  { nombre: "Canela en Astilla", unidad: "gr", proveedor: null },
  { nombre: "Sal", unidad: "gr", proveedor: "Refisal" },
  { nombre: "Salpimienta", unidad: "gr", proveedor: "Preparación" },
  { nombre: "Sazonatodo", unidad: "gr", proveedor: "Badia" },
  { nombre: "Pasta de Ajo", unidad: "gr", proveedor: "Preparación" },
  { nombre: "Caldo de Gallina", unidad: "gr", proveedor: "Knorr" },
  { nombre: "Caldo de Costilla", unidad: "gr", proveedor: "Knorr" },
  { nombre: "Orégano", unidad: "gr", proveedor: null },
  { nombre: "Finas Hierbas", unidad: "gr", proveedor: "El Cauzal" },
  { nombre: "Curri", unidad: "gr", proveedor: null },
  { nombre: "Cúrcuma", unidad: "gr", proveedor: null },
  { nombre: "Jondashi", unidad: "gr", proveedor: null },
  { nombre: "Ajinomoto", unidad: "gr", proveedor: null },
  { nombre: "Cinco Especias", unidad: "gr", proveedor: null },
  { nombre: "Color", unidad: "gr", proveedor: null },
  { nombre: "Nuez Moscada", unidad: "gr", proveedor: "Alfa" },
  { nombre: "Estragon", unidad: "gr", proveedor: null },
  { nombre: "Condimento de Pollo", unidad: "gr", proveedor: "Preparación" },
  { nombre: "Adobo de Pollo", unidad: "gr", proveedor: "Preparación" },
  // Fruits
  { nombre: "Pulpa de Lulo", unidad: "gr", proveedor: null },
  { nombre: "Piña", unidad: "gr", proveedor: null },
  { nombre: "Naranja Valencia", unidad: "gr", proveedor: null },
  { nombre: "Manzana Roja", unidad: "gr", proveedor: null },
  { nombre: "Manzana Verde", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Uva Isabela", unidad: "gr", proveedor: null },
  { nombre: "Limón", unidad: "gr", proveedor: null },
  { nombre: "Zumo de Limón", unidad: "ml", proveedor: "Fruit Juice" },
  { nombre: "Zumo de Naranja", unidad: "ml", proveedor: null },
  { nombre: "Tomate Cherry", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Tomate", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Tomate Seco", unidad: "gr", proveedor: null },
  { nombre: "Arándanos Deshidratados", unidad: "gr", proveedor: "Frutos del Nogal" },
  { nombre: "Mango", unidad: "gr", proveedor: null },
  { nombre: "Aguacate", unidad: "gr", proveedor: null },
  { nombre: "Guayaba (Salsa)", unidad: "gr", proveedor: null },
  // Vegetables
  { nombre: "Cebolla de Huevo Blanca", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Cebolla de Huevo Morada", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Cebolla de Rama", unidad: "gr", proveedor: null },
  { nombre: "Cebolla Puerro", unidad: "gr", proveedor: null },
  { nombre: "Pimentón Rojo", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Champiñones", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Ahuyama", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Espárragos", unidad: "gr", proveedor: null },
  { nombre: "Apio", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Cilantro", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Albahaca", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Hierbabuena", unidad: "gr", proveedor: null },
  { nombre: "Perejil", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Cebollín", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Zanahoria", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Zucchini", unidad: "gr", proveedor: null },
  { nombre: "Calabacín", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Cogollo Europeo", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Lechuga Romana", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Mézclum", unidad: "gr", proveedor: "Pomario" },
  { nombre: "Repollo Morado", unidad: "gr", proveedor: null },
  { nombre: "Brócoli", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Plátano Maduro", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Plátano Verde", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Papa Criolla", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Papa", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Papa Rústica", unidad: "gr", proveedor: "Fritter's" },
  { nombre: "Yuca", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Chip de Arracacha", unidad: "gr", proveedor: "Preparación" },
  { nombre: "Maíz", unidad: "gr", proveedor: "San Valentín" },
  { nombre: "Maíz Tierno", unidad: "gr", proveedor: null },
  // Proteins
  { nombre: "Filete de Pollo (Pechuga)", unidad: "gr", proveedor: "Gam" },
  { nombre: "Pechuga de Pollo", unidad: "gr", proveedor: "Gam" },
  { nombre: "Muslos de Pollo", unidad: "gr", proveedor: "Gam" },
  { nombre: "Pollo Crispy", unidad: "gr", proveedor: "Preparación" },
  { nombre: "Camarones", unidad: "und", proveedor: null },
  { nombre: "Corvina", unidad: "gr", proveedor: "Pescatta" },
  { nombre: "Salmón", unidad: "gr", proveedor: "Pescatta" },
  { nombre: "Solomito de Cerdo", unidad: "gr", proveedor: null },
  { nombre: "Solomito de Res", unidad: "gr", proveedor: null },
  { nombre: "Solomito Molido", unidad: "gr", proveedor: "Carnes FP" },
  { nombre: "Chicharrón en Bloque", unidad: "gr", proveedor: "Gam" },
  { nombre: "Carne de Hamburguesa", unidad: "gr", proveedor: "Preparación" },
  { nombre: "Panceta", unidad: "gr", proveedor: "Gam" },
  { nombre: "Tocineta", unidad: "gr", proveedor: "Rica" },
  { nombre: "Morrillo", unidad: "gr", proveedor: "Carnes FP" },
  { nombre: "Costilla", unidad: "gr", proveedor: "Carnes FP" },
  { nombre: "Huevo", unidad: "und", proveedor: "Local de Aquí" },
  { nombre: "Pulpor", unidad: "gr", proveedor: null },
  // Dairy
  { nombre: "Leche", unidad: "ml", proveedor: "Local de Aquí" },
  { nombre: "Leche de Coco", unidad: "ml", proveedor: "Roland" },
  { nombre: "Crema de Leche", unidad: "ml", proveedor: "Alpina" },
  { nombre: "Queso Mozzarella", unidad: "gr", proveedor: "Colanta" },
  { nombre: "Queso Parmesano", unidad: "gr", proveedor: "Alpina" },
  { nombre: "Bocconcini", unidad: "gr", proveedor: "Dibufala" },
  { nombre: "Burrata", unidad: "gr", proveedor: null },
  { nombre: "Queso Crema", unidad: "gr", proveedor: "Alpina" },
  { nombre: "Suero Costeño", unidad: "gr", proveedor: null },
  { nombre: "Margarina", unidad: "gr", proveedor: "La Buena" },
  { nombre: "Mantequilla Avellanada", unidad: "gr", proveedor: "Preparación" },
  // Grains/Pasta
  { nombre: "Arroz Blanco", unidad: "gr", proveedor: "Caribe" },
  { nombre: "Risotto (Arroz)", unidad: "gr", proveedor: "Castellana" },
  { nombre: "Orzo", unidad: "gr", proveedor: "Conzazoni" },
  { nombre: "Pasta de Lasaña", unidad: "gr", proveedor: "Conzazoni" },
  { nombre: "Ravioles", unidad: "gr", proveedor: null },
  { nombre: "Gnocchi", unidad: "gr", proveedor: "IL Castello" },
  { nombre: "Frijoles Verdes", unidad: "gr", proveedor: null },
  { nombre: "Alverja", unidad: "gr", proveedor: "Alexander Restrepo" },
  { nombre: "Quinoa", unidad: "gr", proveedor: "Organic White Quinoa" },
  // Flours/Breading
  { nombre: "Harina de Trigo", unidad: "gr", proveedor: "La Receta" },
  { nombre: "Harina de Arroz", unidad: "gr", proveedor: "Preparación" },
  { nombre: "Panko", unidad: "gr", proveedor: null },
  { nombre: "Fécula de Maíz", unidad: "gr", proveedor: "Famez S.A" },
  { nombre: "Crotones", unidad: "gr", proveedor: null },
  // Oils/Vinegars
  { nombre: "Aceite Vegetal", unidad: "ml", proveedor: "Gourmet" },
  { nombre: "Aceite de Oliva", unidad: "ml", proveedor: "Sandua" },
  { nombre: "Aceite de Ajonjolí", unidad: "ml", proveedor: "Kadoya" },
  { nombre: "Vinagre Balsámico", unidad: "ml", proveedor: null },
  { nombre: "Vinagre de Jerez", unidad: "ml", proveedor: "Gallo" },
  // Sauces/Condiments
  { nombre: "Salsa de Soya", unidad: "ml", proveedor: "Kikkoman" },
  { nombre: "Sriracha", unidad: "ml", proveedor: "Huy Fong Foods" },
  { nombre: "Mayonesa", unidad: "ml", proveedor: "Bary" },
  { nombre: "Salsa BBQ", unidad: "gr", proveedor: "Bary" },
  { nombre: "Aderezo César", unidad: "gr", proveedor: null },
  { nombre: "Aderezo Waldorf", unidad: "gr", proveedor: null },
  { nombre: "Aderezo de Albahaca", unidad: "gr", proveedor: null },
  { nombre: "Aderezo Cítrico", unidad: "ml", proveedor: null },
  { nombre: "Vinagreta", unidad: "ml", proveedor: "Preparación" },
  { nombre: "Pesto", unidad: "gr", proveedor: null },
  { nombre: "Chimichurri", unidad: "gr", proveedor: null },
  { nombre: "Salsa Bechamel", unidad: "ml", proveedor: "Preparación" },
  { nombre: "Salsa de Tomate", unidad: "gr", proveedor: "Bary" },
  { nombre: "Salsa para Carne", unidad: "gr", proveedor: null },
  { nombre: "Mermelada de Tomate", unidad: "gr", proveedor: null },
  { nombre: "Alioli", unidad: "gr", proveedor: null },
  { nombre: "Salsa Agridulce", unidad: "ml", proveedor: null },
  { nombre: "Escama de Tomate", unidad: "gr", proveedor: "Knorr" },
  { nombre: "Pasta de Tomate", unidad: "gr", proveedor: "Fruco" },
  { nombre: "Demiglace", unidad: "gr", proveedor: "Preparación" },
  { nombre: "Salsa de Alcaparras", unidad: "ml", proveedor: null },
  { nombre: "Reducción de Vino Blanco", unidad: "ml", proveedor: "Preparación" },
  { nombre: "Reducción de Balsámico", unidad: "ml", proveedor: null },
  { nombre: "Hummus", unidad: "gr", proveedor: "Preparación" },
  { nombre: "Picadillo", unidad: "gr", proveedor: "Preparación" },
  { nombre: "Marinada", unidad: "gr", proveedor: "Preparación" },
  { nombre: "Salsa Encocada", unidad: "ml", proveedor: null },
  { nombre: "Mostaza Dijon", unidad: "gr", proveedor: "Hacienda Gourmet" },
  { nombre: "Puré de Papa Criolla", unidad: "gr", proveedor: "Preparación" },
  { nombre: "Puré de Plátano Maduro", unidad: "gr", proveedor: "Preparación" },
  // Alcohols
  { nombre: "Aguardiente", unidad: "ml", proveedor: null },
  { nombre: "Ron Blanco", unidad: "ml", proveedor: "Ron Viejo de Caldas" },
  { nombre: "Vino Tinto", unidad: "ml", proveedor: "Monte Leiva" },
  { nombre: "Vino Blanco", unidad: "ml", proveedor: "Cavic" },
  { nombre: "Triple Sec", unidad: "ml", proveedor: "Brissart" },
  // Baked/Specialty
  { nombre: "Spring Roll Skin", unidad: "gr", proveedor: "Hipermarfish" },
  { nombre: "Pan Bao", unidad: "und", proveedor: "La Caye" },
  { nombre: "Pan de Hamburguesa", unidad: "und", proveedor: null },
  { nombre: "Nuez de Brasil", unidad: "gr", proveedor: "Alfa" },
  { nombre: "Almendras", unidad: "gr", proveedor: "Frutos del Nogal" },
  { nombre: "Ajonjolí", unidad: "gr", proveedor: null },
  { nombre: "Chip de Plátano", unidad: "gr", proveedor: null },
  { nombre: "Quibe", unidad: "und", proveedor: "Farah" },
  { nombre: "Tabulé", unidad: "gr", proveedor: "Second House Products" },
  { nombre: "Chip de Yuca", unidad: "gr", proveedor: null },
  { nombre: "Croqueta de Yuca", unidad: "gr", proveedor: "Toastatas D1" },
  // Misc
  { nombre: "Aceite de Fritura", unidad: "ml", proveedor: "Duma" },
  { nombre: "Sprite", unidad: "ml", proveedor: null },
  { nombre: "Arroz de Coco (Preparación)", unidad: "gr", proveedor: "Preparación" },
];

// ─── ALL 44 DISHES ───
const allDishes: DishDef[] = [
  // === BEBIDAS ===
  {
    nombre: "Lulada",
    categoria: "Bebida",
    porciones_receta: 10,
    tiempo_preparacion: "30 minutos",
    temperatura_coccion: "Fuego alto",
    rendimiento: "1lt mezcla",
    notas: "La preparación base (sin licor) puede ser refrigerada hasta por 1 mes.",
    ingredientes: [
      { nombre: "Agua", cantidad: 800, unidad: "ml" },
      { nombre: "Panela", cantidad: 500, unidad: "gr" },
      { nombre: "Clavos de Olor", cantidad: 10, unidad: "gr" },
      { nombre: "Canela en Astilla", cantidad: 25, unidad: "gr" },
      { nombre: "Pulpa de Lulo", cantidad: 500, unidad: "gr" },
      { nombre: "Aguardiente", cantidad: 1000, unidad: "ml" },
    ],
  },
  {
    nombre: "Piña Colada",
    categoria: "Bebida",
    porciones_receta: 1,
    tiempo_preparacion: "30 minutos",
    temperatura_coccion: null,
    rendimiento: "200ml",
    notas: null,
    ingredientes: [
      { nombre: "Piña", cantidad: 2000, unidad: "gr" },
      { nombre: "Agua", cantidad: 20, unidad: "ml" },
      { nombre: "Ron Blanco", cantidad: 60, unidad: "ml" },
      { nombre: "Leche de Coco", cantidad: 30, unidad: "ml" },
      { nombre: "Hielo", cantidad: 175, unidad: "gr" },
    ],
  },
  {
    nombre: "Sangría",
    categoria: "Bebida",
    porciones_receta: null,
    tiempo_preparacion: "30 minutos",
    temperatura_coccion: null,
    rendimiento: "1lt líquido + 580gr frutas",
    notas: "Preparar preferiblemente el mismo día del servicio.",
    ingredientes: [
      { nombre: "Naranja Valencia", cantidad: 375, unidad: "gr" },
      { nombre: "Manzana Roja", cantidad: 175, unidad: "gr" },
      { nombre: "Vino Tinto", cantidad: 750, unidad: "ml" },
      { nombre: "Uva Isabela", cantidad: 210, unidad: "gr" },
      { nombre: "Triple Sec", cantidad: 120, unidad: "ml" },
      { nombre: "Azúcar", cantidad: 70, unidad: "gr" },
      { nombre: "Zumo de Naranja", cantidad: 100, unidad: "ml" },
      { nombre: "Sprite", cantidad: 200, unidad: "ml" },
    ],
  },
  // === PASABOCA / DECORACIÓN ===
  {
    nombre: "Canastilla de Pasta Filo",
    categoria: "Pasaboca",
    porciones_receta: 1,
    tiempo_preparacion: null,
    temperatura_coccion: "200°C",
    rendimiento: "1 canastilla",
    notas: "Uso sujeto a viabilidad operativa del evento.",
    ingredientes: [
      { nombre: "Margarina", cantidad: 5, unidad: "gr" },
      { nombre: "Spring Roll Skin", cantidad: 15, unidad: "gr" },
      { nombre: "Huevo", cantidad: 1, unidad: "und" },
    ],
  },
  {
    nombre: "Coral",
    categoria: "Pasaboca",
    porciones_receta: 17,
    tiempo_preparacion: "20 minutos",
    temperatura_coccion: "Fuego medio",
    rendimiento: "17 unidades",
    notas: "Decoración crocante para platos.",
    ingredientes: [
      { nombre: "Aceite Vegetal", cantidad: 140, unidad: "ml" },
      { nombre: "Agua", cantidad: 140, unidad: "ml" },
      { nombre: "Harina de Trigo", cantidad: 30, unidad: "gr" },
    ],
  },
  // === ENTRADAS (Ensaladas + Cremas + otros) ===
  {
    nombre: "Ensalada Caprese",
    categoria: "Entrada",
    porciones_receta: 1,
    tiempo_preparacion: "10 minutos",
    temperatura_coccion: null,
    rendimiento: "1 porción",
    notas: null,
    ingredientes: [
      { nombre: "Mézclum", cantidad: 15, unidad: "gr" },
      { nombre: "Bocconcini", cantidad: 65, unidad: "gr" },
      { nombre: "Tomate Cherry", cantidad: 21, unidad: "gr" },
      { nombre: "Vinagre Balsámico", cantidad: 10, unidad: "ml" },
    ],
  },
  {
    nombre: "Ensalada de la Casa",
    categoria: "Entrada",
    porciones_receta: 1,
    tiempo_preparacion: null,
    temperatura_coccion: null,
    rendimiento: "1 porción",
    notas: "Ensalada estándar utilizada en múltiples platos.",
    ingredientes: [
      { nombre: "Mézclum", cantidad: 15, unidad: "gr" },
      { nombre: "Cebolla Puerro", cantidad: 10, unidad: "gr" },
      { nombre: "Tomate Cherry", cantidad: 15, unidad: "gr" },
      { nombre: "Albahaca", cantidad: 10, unidad: "gr" },
      { nombre: "Aderezo de Albahaca", cantidad: 10, unidad: "gr" },
    ],
  },
  {
    nombre: "Ensalada César",
    categoria: "Entrada",
    porciones_receta: 1,
    tiempo_preparacion: "10 minutos",
    temperatura_coccion: null,
    rendimiento: "1 porción",
    notas: "Porción servida en calderito.",
    ingredientes: [
      { nombre: "Cogollo Europeo", cantidad: 30, unidad: "gr" },
      { nombre: "Crotones", cantidad: 15, unidad: "gr" },
      { nombre: "Aderezo César", cantidad: 20, unidad: "gr" },
      { nombre: "Queso Parmesano", cantidad: 10, unidad: "gr" },
    ],
  },
  {
    nombre: "Ensalada Waldorf",
    categoria: "Entrada",
    porciones_receta: null,
    tiempo_preparacion: null,
    temperatura_coccion: null,
    rendimiento: "90gr por porción en caldero",
    notas: "También utilizada como entrada con mayor cantidad.",
    ingredientes: [
      { nombre: "Manzana Verde", cantidad: 1900, unidad: "gr" },
      { nombre: "Nuez de Brasil", cantidad: 250, unidad: "gr" },
      { nombre: "Apio", cantidad: 300, unidad: "gr" },
      { nombre: "Lechuga Romana", cantidad: 100, unidad: "gr" },
      { nombre: "Aderezo Waldorf", cantidad: 200, unidad: "gr" },
    ],
  },
  {
    nombre: "Arancinis",
    categoria: "Entrada",
    porciones_receta: 81,
    tiempo_preparacion: "1 hora",
    temperatura_coccion: "175°C a 190°C",
    rendimiento: "3225gr",
    notas: null,
    ingredientes: [
      { nombre: "Cebolla de Huevo Blanca", cantidad: 250, unidad: "gr" },
      { nombre: "Champiñones", cantidad: 405, unidad: "gr" },
      { nombre: "Risotto (Arroz)", cantidad: 800, unidad: "gr" },
      { nombre: "Vino Blanco", cantidad: 150, unidad: "ml" },
      { nombre: "Estragon", cantidad: 15, unidad: "gr" },
      { nombre: "Caldo de Costilla", cantidad: 30, unidad: "gr" },
      { nombre: "Pasta de Ajo", cantidad: 15, unidad: "gr" },
      { nombre: "Agua", cantidad: 3000, unidad: "ml" },
      { nombre: "Sal", cantidad: 20, unidad: "gr" },
      { nombre: "Tomate Seco", cantidad: 80, unidad: "gr" },
      { nombre: "Queso Mozzarella", cantidad: 370, unidad: "gr" },
      { nombre: "Harina de Trigo", cantidad: 500, unidad: "gr" },
      { nombre: "Panko", cantidad: 800, unidad: "gr" },
    ],
  },
  {
    nombre: "Crema de Ahuyama",
    categoria: "Entrada",
    porciones_receta: null,
    tiempo_preparacion: "1 hora",
    temperatura_coccion: "Fuego alto / bajo",
    rendimiento: null,
    notas: null,
    ingredientes: [
      { nombre: "Cebolla de Huevo Blanca", cantidad: 2035, unidad: "gr" },
      { nombre: "Ahuyama", cantidad: 5355, unidad: "gr" },
      { nombre: "Pasta de Ajo", cantidad: 40, unidad: "gr" },
      { nombre: "Sal", cantidad: 60, unidad: "gr" },
      { nombre: "Caldo de Gallina", cantidad: 45, unidad: "gr" },
      { nombre: "Agua", cantidad: 4000, unidad: "ml" },
      { nombre: "Leche de Coco", cantidad: 1600, unidad: "ml" },
      { nombre: "Fécula de Maíz", cantidad: 150, unidad: "gr" },
    ],
  },
  {
    nombre: "Crema de Champiñón",
    categoria: "Entrada",
    porciones_receta: null,
    tiempo_preparacion: "30 minutos",
    temperatura_coccion: "Fuego medio-alto",
    rendimiento: "1175gr",
    notas: "Conservar refrigerada hasta 8 días, congelada hasta 1 mes.",
    ingredientes: [
      { nombre: "Champiñones", cantidad: 210, unidad: "gr" },
      { nombre: "Cebolla de Huevo Blanca", cantidad: 230, unidad: "gr" },
      { nombre: "Sal", cantidad: 10, unidad: "gr" },
      { nombre: "Aceite Vegetal", cantidad: 10, unidad: "ml" },
      { nombre: "Apio", cantidad: 10, unidad: "gr" },
      { nombre: "Agua", cantidad: 500, unidad: "ml" },
      { nombre: "Caldo de Gallina", cantidad: 10, unidad: "gr" },
      { nombre: "Crema de Leche", cantidad: 245, unidad: "ml" },
    ],
  },
  {
    nombre: "Crema de Maíz",
    categoria: "Entrada",
    porciones_receta: null,
    tiempo_preparacion: "1 hora 50 minutos",
    temperatura_coccion: "Fuego medio",
    rendimiento: "21lt",
    notas: null,
    ingredientes: [
      { nombre: "Maíz", cantidad: 8000, unidad: "gr" },
      { nombre: "Pasta de Ajo", cantidad: 45, unidad: "gr" },
      { nombre: "Leche", cantidad: 6310, unidad: "ml" },
      { nombre: "Cebolla de Huevo Blanca", cantidad: 755, unidad: "gr" },
      { nombre: "Caldo de Gallina", cantidad: 150, unidad: "gr" },
      { nombre: "Agua", cantidad: 9500, unidad: "ml" },
      { nombre: "Fécula de Maíz", cantidad: 300, unidad: "gr" },
    ],
  },
  {
    nombre: "Crema de Tomate",
    categoria: "Entrada",
    porciones_receta: null,
    tiempo_preparacion: "30 minutos",
    temperatura_coccion: "Fuego medio-alto",
    rendimiento: "1135gr",
    notas: "Conservar refrigerada hasta 8 días, congelada hasta 1 mes.",
    ingredientes: [
      { nombre: "Albahaca", cantidad: 15, unidad: "gr" },
      { nombre: "Tomate", cantidad: 375, unidad: "gr" },
      { nombre: "Aceite Vegetal", cantidad: 80, unidad: "ml" },
      { nombre: "Pasta de Ajo", cantidad: 20, unidad: "gr" },
      { nombre: "Cebolla de Huevo Blanca", cantidad: 270, unidad: "gr" },
      { nombre: "Agua", cantidad: 500, unidad: "ml" },
      { nombre: "Sal", cantidad: 15, unidad: "gr" },
      { nombre: "Escama de Tomate", cantidad: 65, unidad: "gr" },
      { nombre: "Azúcar", cantidad: 20, unidad: "gr" },
    ],
  },
  {
    nombre: "Encocado de Plátano Maduro con Camarones",
    categoria: "Entrada",
    porciones_receta: 1,
    tiempo_preparacion: null,
    temperatura_coccion: null,
    rendimiento: "1 plato",
    notas: "Los chip de arracacha los hacen en cocina.",
    ingredientes: [
      { nombre: "Puré de Plátano Maduro", cantidad: 120, unidad: "gr" },
      { nombre: "Pimentón Rojo", cantidad: 40, unidad: "gr" },
      { nombre: "Cebolla de Huevo Blanca", cantidad: 40, unidad: "gr" },
      { nombre: "Leche de Coco", cantidad: 200, unidad: "ml" },
      { nombre: "Pasta de Ajo", cantidad: 5, unidad: "gr" },
      { nombre: "Crema de Leche", cantidad: 200, unidad: "ml" },
      { nombre: "Camarones", cantidad: 12, unidad: "und" },
      { nombre: "Jondashi", cantidad: 5, unidad: "gr" },
      { nombre: "Ajinomoto", cantidad: 5, unidad: "gr" },
      { nombre: "Curri", cantidad: 2.5, unidad: "gr" },
      { nombre: "Cilantro", cantidad: 40, unidad: "gr" },
      { nombre: "Chip de Arracacha", cantidad: 10, unidad: "gr" },
      { nombre: "Suero Costeño", cantidad: 30, unidad: "gr" },
    ],
  },
  {
    nombre: "Mini Bao de Camarón Crispy",
    categoria: "Entrada",
    porciones_receta: 1,
    tiempo_preparacion: "15 minutos",
    temperatura_coccion: "180°C",
    rendimiento: "1 mini bao",
    notas: null,
    ingredientes: [
      { nombre: "Sriracha", cantidad: 10, unidad: "ml" },
      { nombre: "Mayonesa", cantidad: 20, unidad: "ml" },
      { nombre: "Salsa de Soya", cantidad: 10, unidad: "ml" },
      { nombre: "Repollo Morado", cantidad: 5, unidad: "gr" },
      { nombre: "Hierbabuena", cantidad: 1, unidad: "gr" },
      { nombre: "Albahaca", cantidad: 1, unidad: "gr" },
      { nombre: "Salpimienta", cantidad: 2.5, unidad: "gr" },
      { nombre: "Miel de Maple", cantidad: 10, unidad: "ml" },
      { nombre: "Vinagre de Jerez", cantidad: 5, unidad: "ml" },
      { nombre: "Aceite de Ajonjolí", cantidad: 5, unidad: "ml" },
      { nombre: "Pan Bao", cantidad: 1, unidad: "und" },
      { nombre: "Camarones", cantidad: 2, unidad: "und" },
      { nombre: "Harina de Trigo", cantidad: 10, unidad: "gr" },
      { nombre: "Panko", cantidad: 10, unidad: "gr" },
      { nombre: "Agua", cantidad: 15, unidad: "ml" },
      { nombre: "Jondashi", cantidad: 1.5, unidad: "gr" },
    ],
  },
  {
    nombre: "Mini Bao de Pollo Crispy",
    categoria: "Entrada",
    porciones_receta: 5,
    tiempo_preparacion: null,
    temperatura_coccion: "Fuego medio-alto",
    rendimiento: "5 bao",
    notas: "Bao refrigerado: regenerar en horno vapor 2 min o samovar 10-15 min.",
    ingredientes: [
      { nombre: "Zanahoria", cantidad: 90, unidad: "gr" },
      { nombre: "Pan Bao", cantidad: 5, unidad: "und" },
      { nombre: "Filete de Pollo (Pechuga)", cantidad: 180, unidad: "gr" },
      { nombre: "Vinagre de Jerez", cantidad: 16, unidad: "ml" },
      { nombre: "Miel de Maple", cantidad: 8, unidad: "ml" },
      { nombre: "Albahaca", cantidad: 2, unidad: "gr" },
      { nombre: "Hierbabuena", cantidad: 2, unidad: "gr" },
      { nombre: "Aceite de Ajonjolí", cantidad: 8, unidad: "ml" },
      { nombre: "Zumo de Limón", cantidad: 8, unidad: "ml" },
      { nombre: "Salpimienta", cantidad: 3, unidad: "gr" },
      { nombre: "Panko", cantidad: 250, unidad: "gr" },
      { nombre: "Aceite de Fritura", cantidad: 1500, unidad: "ml" },
      { nombre: "Mayonesa", cantidad: 250, unidad: "ml" },
      { nombre: "Sriracha", cantidad: 50, unidad: "ml" },
    ],
  },
  {
    nombre: "Plátano Maduro Asado con Burrata",
    categoria: "Entrada",
    porciones_receta: 1,
    tiempo_preparacion: "20 minutos",
    temperatura_coccion: "180°C / 250°C",
    rendimiento: "1 porción",
    notas: null,
    ingredientes: [
      { nombre: "Plátano Maduro", cantidad: 600, unidad: "gr" },
      { nombre: "Burrata", cantidad: 50, unidad: "gr" },
      { nombre: "Margarina", cantidad: 20, unidad: "gr" },
      { nombre: "Guayaba (Salsa)", cantidad: 40, unidad: "gr" },
      { nombre: "Queso Parmesano", cantidad: 10, unidad: "gr" },
    ],
  },
  // === FUERTES ===
  {
    nombre: "Bowl Toscano",
    categoria: "Fuerte",
    porciones_receta: 1,
    tiempo_preparacion: "30 minutos",
    temperatura_coccion: "Fuego medio-alto",
    rendimiento: "600gr plato completo",
    notas: "El orzo se cocina un día antes.",
    ingredientes: [
      { nombre: "Agua", cantidad: 1000, unidad: "ml" },
      { nombre: "Sal", cantidad: 17, unidad: "gr" },
      { nombre: "Orzo", cantidad: 80, unidad: "gr" },
      { nombre: "Champiñones", cantidad: 40, unidad: "gr" },
      { nombre: "Tomate Cherry", cantidad: 45, unidad: "gr" },
      { nombre: "Filete de Pollo (Pechuga)", cantidad: 180, unidad: "gr" },
      { nombre: "Mézclum", cantidad: 10, unidad: "gr" },
      { nombre: "Aceite Vegetal", cantidad: 40, unidad: "ml" },
      { nombre: "Sazonatodo", cantidad: 20, unidad: "gr" },
      { nombre: "Pesto", cantidad: 50, unidad: "gr" },
      { nombre: "Vinagreta", cantidad: 10, unidad: "ml" },
      { nombre: "Finas Hierbas", cantidad: 5, unidad: "gr" },
    ],
  },
  {
    nombre: "Hamburguesa Sweet Pesto",
    categoria: "Fuerte",
    porciones_receta: 7,
    tiempo_preparacion: "10-15 minutos montaje",
    temperatura_coccion: "150°C / 300°C",
    rendimiento: "7 hamburguesas",
    notas: "La carne se hace con cordón de solomito de res molida.",
    ingredientes: [
      { nombre: "Pan de Hamburguesa", cantidad: 7, unidad: "und" },
      { nombre: "Carne de Hamburguesa", cantidad: 1050, unidad: "gr" },
      { nombre: "Panceta", cantidad: 280, unidad: "gr" },
      { nombre: "Salsa BBQ", cantidad: 10, unidad: "gr" },
      { nombre: "Miel de Maple", cantidad: 80, unidad: "ml" },
      { nombre: "Mermelada de Tomate", cantidad: 210, unidad: "gr" },
      { nombre: "Tomate", cantidad: 100, unidad: "gr" },
      { nombre: "Cogollo Europeo", cantidad: 70, unidad: "gr" },
      { nombre: "Chimichurri", cantidad: 105, unidad: "gr" },
      { nombre: "Pesto", cantidad: 35, unidad: "gr" },
      { nombre: "Bocconcini", cantidad: 245, unidad: "gr" },
      { nombre: "Alioli", cantidad: 210, unidad: "gr" },
      { nombre: "Papa Rústica", cantidad: 280, unidad: "gr" },
    ],
  },
  {
    nombre: "Lasaña de Pollo",
    categoria: "Fuerte",
    porciones_receta: 3,
    tiempo_preparacion: "1 hora",
    temperatura_coccion: "180°C",
    rendimiento: "3 porciones",
    notas: "Puede prepararse y congelarse hasta 1 mes antes de hornear.",
    ingredientes: [
      { nombre: "Pechuga de Pollo", cantidad: 900, unidad: "gr" },
      { nombre: "Agua", cantidad: 2000, unidad: "ml" },
      { nombre: "Caldo de Gallina", cantidad: 50, unidad: "gr" },
      { nombre: "Pasta de Lasaña", cantidad: 30, unidad: "gr" },
      { nombre: "Queso Mozzarella", cantidad: 50, unidad: "gr" },
      { nombre: "Salsa Bechamel", cantidad: 100, unidad: "ml" },
    ],
  },
  {
    nombre: "Lasaña de Solomito",
    categoria: "Fuerte",
    porciones_receta: null,
    tiempo_preparacion: "1 hora",
    temperatura_coccion: "160°C",
    rendimiento: null,
    notas: "La receta original es con Zabaleta Molida.",
    ingredientes: [
      { nombre: "Solomito Molido", cantidad: 3000, unidad: "gr" },
      { nombre: "Cebolla de Huevo Blanca", cantidad: 300, unidad: "gr" },
      { nombre: "Margarina", cantidad: 30, unidad: "gr" },
      { nombre: "Salsa de Tomate", cantidad: 300, unidad: "gr" },
      { nombre: "Salsa para Carne", cantidad: 200, unidad: "gr" },
      { nombre: "Vino Tinto", cantidad: 500, unidad: "ml" },
      { nombre: "Sal", cantidad: 45, unidad: "gr" },
      { nombre: "Orégano", cantidad: 20, unidad: "gr" },
      { nombre: "Albahaca", cantidad: 30, unidad: "gr" },
      { nombre: "Pasta de Lasaña", cantidad: 270, unidad: "gr" },
      { nombre: "Queso Parmesano", cantidad: 300, unidad: "gr" },
      { nombre: "Salsa Bechamel", cantidad: 1500, unidad: "ml" },
      { nombre: "Queso Mozzarella", cantidad: 500, unidad: "gr" },
    ],
  },
  {
    nombre: "Medallones de Pollo con Ravioles",
    categoria: "Fuerte",
    porciones_receta: 1,
    tiempo_preparacion: "40 minutos",
    temperatura_coccion: "180°C",
    rendimiento: "1 plato",
    notas: null,
    ingredientes: [
      { nombre: "Espárragos", cantidad: 60, unidad: "gr" },
      { nombre: "Agua", cantidad: 2000, unidad: "ml" },
      { nombre: "Sal", cantidad: 15, unidad: "gr" },
      { nombre: "Ravioles", cantidad: 120, unidad: "gr" },
      { nombre: "Filete de Pollo (Pechuga)", cantidad: 180, unidad: "gr" },
      { nombre: "Condimento de Pollo", cantidad: 20, unidad: "gr" },
      { nombre: "Queso Parmesano", cantidad: 10, unidad: "gr" },
      { nombre: "Aceite de Oliva", cantidad: 20, unidad: "ml" },
      { nombre: "Sazonatodo", cantidad: 5, unidad: "gr" },
      { nombre: "Tomate Cherry", cantidad: 15, unidad: "gr" },
      { nombre: "Finas Hierbas", cantidad: 5, unidad: "gr" },
    ],
  },
  {
    nombre: "Mini Bowl Árabe",
    categoria: "Fuerte",
    porciones_receta: 1,
    tiempo_preparacion: null,
    temperatura_coccion: "Fuego alto",
    rendimiento: "1 plato",
    notas: "El aceite de fritura de quibe puede reutilizarse 4-5 veces.",
    ingredientes: [
      { nombre: "Arroz Blanco", cantidad: 500, unidad: "gr" },
      { nombre: "Aceite Vegetal", cantidad: 30, unidad: "ml" },
      { nombre: "Quibe", cantidad: 2, unidad: "und" },
      { nombre: "Tabulé", cantidad: 50, unidad: "gr" },
      { nombre: "Agua", cantidad: 50, unidad: "ml" },
      { nombre: "Aceite de Fritura", cantidad: 1000, unidad: "ml" },
      { nombre: "Cinco Especias", cantidad: 10, unidad: "gr" },
      { nombre: "Hummus", cantidad: 20, unidad: "gr" },
      { nombre: "Picadillo", cantidad: 50, unidad: "gr" },
      { nombre: "Almendras", cantidad: 30, unidad: "gr" },
      { nombre: "Perejil", cantidad: 5, unidad: "gr" },
      { nombre: "Aceite de Ajonjolí", cantidad: 5, unidad: "ml" },
    ],
  },
  {
    nombre: "Mini Bowl Costeño",
    categoria: "Fuerte",
    porciones_receta: 1,
    tiempo_preparacion: null,
    temperatura_coccion: null,
    rendimiento: null,
    notas: null,
    ingredientes: [
      { nombre: "Arroz de Coco (Preparación)", cantidad: 150, unidad: "gr" },
      { nombre: "Chip de Yuca", cantidad: 20, unidad: "gr" },
      { nombre: "Pulpor", cantidad: 120, unidad: "gr" },
      { nombre: "Queso Crema", cantidad: 30, unidad: "gr" },
      { nombre: "Sal", cantidad: 5, unidad: "gr" },
      { nombre: "Leche", cantidad: 10, unidad: "ml" },
      { nombre: "Zumo de Limón", cantidad: 5, unidad: "ml" },
      { nombre: "Cilantro", cantidad: 5, unidad: "gr" },
      { nombre: "Cebollín", cantidad: 5, unidad: "gr" },
      { nombre: "Maíz Tierno", cantidad: 20, unidad: "gr" },
    ],
  },
  {
    nombre: "Mini Bowl Orzo con Maicitos",
    categoria: "Fuerte",
    porciones_receta: 1,
    tiempo_preparacion: null,
    temperatura_coccion: "Fuego alto",
    rendimiento: null,
    notas: null,
    ingredientes: [
      { nombre: "Filete de Pollo (Pechuga)", cantidad: 120, unidad: "gr" },
      { nombre: "Tocineta", cantidad: 100, unidad: "gr" },
      { nombre: "Orzo", cantidad: 70, unidad: "gr" },
      { nombre: "Cebolla de Huevo Blanca", cantidad: 170, unidad: "gr" },
      { nombre: "Aceite Vegetal", cantidad: 30, unidad: "ml" },
      { nombre: "Sal", cantidad: 5, unidad: "gr" },
      { nombre: "Vino Blanco", cantidad: 50, unidad: "ml" },
      { nombre: "Estragon", cantidad: 15, unidad: "gr" },
      { nombre: "Crema de Leche", cantidad: 750, unidad: "ml" },
      { nombre: "Caldo de Gallina", cantidad: 15, unidad: "gr" },
      { nombre: "Fécula de Maíz", cantidad: 15, unidad: "gr" },
      { nombre: "Agua", cantidad: 1030, unidad: "ml" },
      { nombre: "Hielo", cantidad: 300, unidad: "gr" },
      { nombre: "Maíz", cantidad: 50, unidad: "gr" },
    ],
  },
  {
    nombre: "Panceta al Estilo Selecta",
    categoria: "Fuerte",
    porciones_receta: 4,
    tiempo_preparacion: "1 hora",
    temperatura_coccion: "180°C / 300°C",
    rendimiento: "875gr chicharrón crocante",
    notas: "4 porciones de 180g cada una.",
    ingredientes: [
      { nombre: "Chicharrón en Bloque", cantidad: 1150, unidad: "gr" },
      { nombre: "Adobo de Pollo", cantidad: 40, unidad: "gr" },
      { nombre: "Puré de Papa Criolla", cantidad: 150, unidad: "gr" },
      { nombre: "Cebolla de Huevo Blanca", cantidad: 320, unidad: "gr" },
      { nombre: "Cebolla de Huevo Morada", cantidad: 160, unidad: "gr" },
      { nombre: "Pimentón Rojo", cantidad: 130, unidad: "gr" },
      { nombre: "Cilantro", cantidad: 15, unidad: "gr" },
      { nombre: "Salpimienta", cantidad: 2.5, unidad: "gr" },
      { nombre: "Limón", cantidad: 150, unidad: "gr" },
      { nombre: "Miel de Maple", cantidad: 40, unidad: "ml" },
      { nombre: "Marinada", cantidad: 60, unidad: "gr" },
      { nombre: "Cogollo Europeo", cantidad: 30, unidad: "gr" },
      { nombre: "Crotones", cantidad: 15, unidad: "gr" },
      { nombre: "Aderezo César", cantidad: 20, unidad: "gr" },
    ],
  },
  {
    nombre: "Pesca Blanca en Mantequilla Finas Hierbas",
    categoria: "Fuerte",
    porciones_receta: 16,
    tiempo_preparacion: "50 minutos",
    temperatura_coccion: "175°C",
    rendimiento: "16 porciones",
    notas: "Pesca puede variar según disponibilidad del proveedor.",
    ingredientes: [
      { nombre: "Corvina", cantidad: 3040, unidad: "gr" },
      { nombre: "Salpimienta", cantidad: 80, unidad: "gr" },
      { nombre: "Pasta de Ajo", cantidad: 48, unidad: "gr" },
      { nombre: "Harina de Arroz", cantidad: 150, unidad: "gr" },
      { nombre: "Aceite Vegetal", cantidad: 135, unidad: "ml" },
      { nombre: "Margarina", cantidad: 70, unidad: "gr" },
    ],
  },
  {
    nombre: "Pesca Blanca Sobre Cama Encocada",
    categoria: "Fuerte",
    porciones_receta: 1,
    tiempo_preparacion: "1 hora",
    temperatura_coccion: "170°C",
    rendimiento: "1 porción",
    notas: "El tiempo de cocción varía según si el pescado está congelado.",
    ingredientes: [
      { nombre: "Corvina", cantidad: 436, unidad: "gr" },
      { nombre: "Salpimienta", cantidad: 5, unidad: "gr" },
      { nombre: "Pasta de Ajo", cantidad: 2, unidad: "gr" },
      { nombre: "Harina de Arroz", cantidad: 30, unidad: "gr" },
      { nombre: "Aceite Vegetal", cantidad: 8, unidad: "ml" },
      { nombre: "Margarina", cantidad: 5, unidad: "gr" },
      { nombre: "Salsa Encocada", cantidad: 100, unidad: "ml" },
      { nombre: "Camarones", cantidad: 12, unidad: "und" },
      { nombre: "Croqueta de Yuca", cantidad: 125, unidad: "gr" },
      { nombre: "Aceite de Fritura", cantidad: 1000, unidad: "ml" },
    ],
  },
  {
    nombre: "Salmón al Grill",
    categoria: "Fuerte",
    porciones_receta: 1,
    tiempo_preparacion: "40 minutos",
    temperatura_coccion: "170°C",
    rendimiento: "160gr salmón cocinado",
    notas: "Timbal de plátano = puré de plátano en molde redondo 9cm.",
    ingredientes: [
      { nombre: "Salmón", cantidad: 190, unidad: "gr" },
      { nombre: "Salpimienta", cantidad: 5, unidad: "gr" },
      { nombre: "Aceite Vegetal", cantidad: 15, unidad: "ml" },
      { nombre: "Puré de Plátano Maduro", cantidad: 150, unidad: "gr" },
      { nombre: "Reducción de Vino Blanco", cantidad: 60, unidad: "ml" },
    ],
  },
  {
    nombre: "Sancocho Trifásico",
    categoria: "Fuerte",
    porciones_receta: null,
    tiempo_preparacion: "1 hora 20 minutos",
    temperatura_coccion: "Fuego alto",
    rendimiento: null,
    notas: null,
    ingredientes: [
      { nombre: "Morrillo", cantidad: 1500, unidad: "gr" },
      { nombre: "Muslos de Pollo", cantidad: 1500, unidad: "gr" },
      { nombre: "Costilla", cantidad: 1500, unidad: "gr" },
      { nombre: "Papa", cantidad: 1715, unidad: "gr" },
      { nombre: "Yuca", cantidad: 920, unidad: "gr" },
      { nombre: "Plátano Verde", cantidad: 730, unidad: "gr" },
      { nombre: "Sal", cantidad: 60, unidad: "gr" },
      { nombre: "Caldo de Gallina", cantidad: 170, unidad: "gr" },
      { nombre: "Color", cantidad: 20, unidad: "gr" },
      { nombre: "Cebolla de Rama", cantidad: 140, unidad: "gr" },
      { nombre: "Tomate", cantidad: 300, unidad: "gr" },
      { nombre: "Cebolla de Huevo Blanca", cantidad: 200, unidad: "gr" },
      { nombre: "Pasta de Ajo", cantidad: 30, unidad: "gr" },
      { nombre: "Pimentón Rojo", cantidad: 200, unidad: "gr" },
      { nombre: "Cilantro", cantidad: 100, unidad: "gr" },
      { nombre: "Agua", cantidad: 200, unidad: "ml" },
    ],
  },
  {
    nombre: "Solomito de Cerdo Albardado",
    categoria: "Fuerte",
    porciones_receta: 1,
    tiempo_preparacion: "30 minutos",
    temperatura_coccion: "180°C",
    rendimiento: "1 porción",
    notas: null,
    ingredientes: [
      { nombre: "Solomito de Cerdo", cantidad: 170, unidad: "gr" },
      { nombre: "Tocineta", cantidad: 10, unidad: "gr" },
      { nombre: "Salsa de Alcaparras", cantidad: 50, unidad: "ml" },
      { nombre: "Papa Rústica", cantidad: 150, unidad: "gr" },
      { nombre: "Cogollo Europeo", cantidad: 20, unidad: "gr" },
      { nombre: "Mango", cantidad: 50, unidad: "gr" },
      { nombre: "Aguacate", cantidad: 75, unidad: "gr" },
      { nombre: "Aderezo Cítrico", cantidad: 10, unidad: "ml" },
      { nombre: "Sazonatodo", cantidad: 5, unidad: "gr" },
      { nombre: "Salpimienta", cantidad: 10, unidad: "gr" },
    ],
  },
  {
    nombre: "Solomito Rostizado con Gnocchi",
    categoria: "Fuerte",
    porciones_receta: 1,
    tiempo_preparacion: "20 minutos",
    temperatura_coccion: "Grill",
    rendimiento: "1 plato",
    notas: "Gnocchi debe ser marca IL Castello.",
    ingredientes: [
      { nombre: "Solomito de Res", cantidad: 180, unidad: "gr" },
      { nombre: "Mantequilla Avellanada", cantidad: 10, unidad: "gr" },
      { nombre: "Gnocchi", cantidad: 100, unidad: "gr" },
      { nombre: "Queso Parmesano", cantidad: 10, unidad: "gr" },
      { nombre: "Agua", cantidad: 1000, unidad: "ml" },
      { nombre: "Salpimienta", cantidad: 10, unidad: "gr" },
      { nombre: "Mézclum", cantidad: 15, unidad: "gr" },
      { nombre: "Bocconcini", cantidad: 65, unidad: "gr" },
      { nombre: "Tomate Cherry", cantidad: 21, unidad: "gr" },
      { nombre: "Reducción de Balsámico", cantidad: 10, unidad: "ml" },
    ],
  },
  // === GUARNICIONES ===
  {
    nombre: "Arroz al Wok",
    categoria: "Guarnición",
    porciones_receta: 1,
    tiempo_preparacion: "30 minutos",
    temperatura_coccion: "Fuego medio-alto",
    rendimiento: "400gr plato completo",
    notas: "Arroz se cocina un día antes. Vegetales pueden dejarse picados.",
    ingredientes: [
      { nombre: "Cebolla de Huevo Blanca", cantidad: 150, unidad: "gr" },
      { nombre: "Cebolla de Huevo Morada", cantidad: 65, unidad: "gr" },
      { nombre: "Zanahoria", cantidad: 310, unidad: "gr" },
      { nombre: "Pimentón Rojo", cantidad: 115, unidad: "gr" },
      { nombre: "Arroz Blanco", cantidad: 80, unidad: "gr" },
      { nombre: "Aceite Vegetal", cantidad: 10, unidad: "ml" },
      { nombre: "Sal", cantidad: 1.5, unidad: "gr" },
      { nombre: "Zucchini", cantidad: 15, unidad: "gr" },
      { nombre: "Calabacín", cantidad: 15, unidad: "gr" },
      { nombre: "Pollo Crispy", cantidad: 140, unidad: "gr" },
      { nombre: "Ajinomoto", cantidad: 5, unidad: "gr" },
      { nombre: "Aceite de Ajonjolí", cantidad: 5, unidad: "ml" },
      { nombre: "Jondashi", cantidad: 10, unidad: "gr" },
      { nombre: "Salsa de Soya", cantidad: 20, unidad: "ml" },
      { nombre: "Cebollín", cantidad: 5, unidad: "gr" },
      { nombre: "Ajonjolí", cantidad: 10, unidad: "gr" },
      { nombre: "Chip de Plátano", cantidad: 30, unidad: "gr" },
      { nombre: "Salsa Agridulce", cantidad: 80, unidad: "ml" },
    ],
  },
  {
    nombre: "Arroz al Curri",
    categoria: "Guarnición",
    porciones_receta: null,
    tiempo_preparacion: null,
    temperatura_coccion: "Fuego alto-medio",
    rendimiento: null,
    notas: null,
    ingredientes: [
      { nombre: "Arroz Blanco", cantidad: 500, unidad: "gr" },
      { nombre: "Agua", cantidad: 1000, unidad: "ml" },
      { nombre: "Aceite Vegetal", cantidad: 40, unidad: "ml" },
      { nombre: "Sal", cantidad: 7.5, unidad: "gr" },
      { nombre: "Pasta de Ajo", cantidad: 5, unidad: "gr" },
      { nombre: "Cúrcuma", cantidad: 5, unidad: "gr" },
      { nombre: "Curri", cantidad: 5, unidad: "gr" },
      { nombre: "Filete de Pollo (Pechuga)", cantidad: 120, unidad: "gr" },
      { nombre: "Zanahoria", cantidad: 240, unidad: "gr" },
      { nombre: "Brócoli", cantidad: 100, unidad: "gr" },
    ],
  },
  {
    nombre: "Arroz de Arándanos",
    categoria: "Guarnición",
    porciones_receta: 8,
    tiempo_preparacion: "1 hora 30 minutos",
    temperatura_coccion: "Fuego alto / medio",
    rendimiento: null,
    notas: null,
    ingredientes: [
      { nombre: "Arroz Blanco", cantidad: 480, unidad: "gr" },
      { nombre: "Aceite Vegetal", cantidad: 30, unidad: "ml" },
      { nombre: "Sal", cantidad: 10, unidad: "gr" },
      { nombre: "Pasta de Ajo", cantidad: 10, unidad: "gr" },
      { nombre: "Almendras", cantidad: 100, unidad: "gr" },
      { nombre: "Arándanos Deshidratados", cantidad: 185, unidad: "gr" },
      { nombre: "Perejil", cantidad: 40, unidad: "gr" },
      { nombre: "Miel de Maple", cantidad: 50, unidad: "ml" },
    ],
  },
  {
    nombre: "Arroz de Coco",
    categoria: "Guarnición",
    porciones_receta: 65,
    tiempo_preparacion: "30 minutos",
    temperatura_coccion: "Fuego medio",
    rendimiento: "65 porciones de 150gr",
    notas: null,
    ingredientes: [
      { nombre: "Arroz Blanco", cantidad: 3300, unidad: "gr" },
      { nombre: "Dulce Quemado", cantidad: 130, unidad: "ml" },
      { nombre: "Agua", cantidad: 3000, unidad: "ml" },
      { nombre: "Leche de Coco", cantidad: 3000, unidad: "ml" },
      { nombre: "Salpimienta", cantidad: 120, unidad: "gr" },
      { nombre: "Aceite Vegetal", cantidad: 250, unidad: "ml" },
      { nombre: "Azúcar", cantidad: 500, unidad: "gr" },
    ],
  },
  {
    nombre: "Arroz Frito",
    categoria: "Guarnición",
    porciones_receta: null,
    tiempo_preparacion: "1 hora",
    temperatura_coccion: "Fuego medio",
    rendimiento: "6.5kg arroz",
    notas: "Conservar refrigerado máximo 1 día.",
    ingredientes: [
      { nombre: "Arroz Blanco", cantidad: 1500, unidad: "gr" },
      { nombre: "Zanahoria", cantidad: 935, unidad: "gr" },
      { nombre: "Maíz", cantidad: 1000, unidad: "gr" },
      { nombre: "Aceite Vegetal", cantidad: 50, unidad: "ml" },
      { nombre: "Agua", cantidad: 3000, unidad: "ml" },
      { nombre: "Alverja", cantidad: 1000, unidad: "gr" },
      { nombre: "Papa Criolla", cantidad: 4000, unidad: "gr" },
      { nombre: "Pasta de Ajo", cantidad: 100, unidad: "gr" },
      { nombre: "Adobo de Pollo", cantidad: 120, unidad: "gr" },
      { nombre: "Sal", cantidad: 100, unidad: "gr" },
      { nombre: "Demiglace", cantidad: 60, unidad: "gr" },
      { nombre: "Sazonatodo", cantidad: 90, unidad: "gr" },
    ],
  },
  {
    nombre: "Arroz Simple",
    categoria: "Guarnición",
    porciones_receta: 30,
    tiempo_preparacion: "30 minutos",
    temperatura_coccion: "Fuego alto / bajo",
    rendimiento: "30 porciones de 120gr",
    notas: null,
    ingredientes: [
      { nombre: "Arroz Blanco", cantidad: 1600, unidad: "gr" },
      { nombre: "Aceite Vegetal", cantidad: 50, unidad: "ml" },
      { nombre: "Sal", cantidad: 45, unidad: "gr" },
      { nombre: "Pasta de Ajo", cantidad: 15, unidad: "gr" },
      { nombre: "Agua", cantidad: 3200, unidad: "ml" },
    ],
  },
  {
    nombre: "Consomé de Pollo",
    categoria: "Guarnición",
    porciones_receta: 50,
    tiempo_preparacion: null,
    temperatura_coccion: null,
    rendimiento: "50 platos",
    notas: "Se prepara previamente y se envía al evento para terminación en sitio.",
    ingredientes: [
      { nombre: "Pechuga de Pollo", cantidad: 2000, unidad: "gr" },
      { nombre: "Pimentón Rojo", cantidad: 365, unidad: "gr" },
      { nombre: "Cebolla de Huevo Blanca", cantidad: 270, unidad: "gr" },
      { nombre: "Cilantro", cantidad: 200, unidad: "gr" },
      { nombre: "Pasta de Ajo", cantidad: 40, unidad: "gr" },
      { nombre: "Agua", cantidad: 2000, unidad: "ml" },
      { nombre: "Caldo de Gallina", cantidad: 80, unidad: "gr" },
    ],
  },
  {
    nombre: "Crepes",
    categoria: "Guarnición",
    porciones_receta: 36,
    tiempo_preparacion: null,
    temperatura_coccion: "Fuego bajo",
    rendimiento: "36 crepes",
    notas: null,
    ingredientes: [
      { nombre: "Harina de Trigo", cantidad: 625, unidad: "gr" },
      { nombre: "Huevo", cantidad: 10, unidad: "und" },
      { nombre: "Leche", cantidad: 1250, unidad: "ml" },
      { nombre: "Aceite Vegetal", cantidad: 250, unidad: "ml" },
      { nombre: "Azúcar", cantidad: 25, unidad: "gr" },
      { nombre: "Sal", cantidad: 5, unidad: "gr" },
      { nombre: "Finas Hierbas", cantidad: 8, unidad: "gr" },
    ],
  },
  {
    nombre: "Frijoles",
    categoria: "Guarnición",
    porciones_receta: 14,
    tiempo_preparacion: "1 hora 30 minutos",
    temperatura_coccion: "Fuego alto / medio-bajo",
    rendimiento: "14 platos",
    notas: null,
    ingredientes: [
      { nombre: "Frijoles Verdes", cantidad: 2000, unidad: "gr" },
      { nombre: "Agua", cantidad: 5000, unidad: "ml" },
      { nombre: "Caldo de Costilla", cantidad: 90, unidad: "gr" },
      { nombre: "Sal", cantidad: 40, unidad: "gr" },
      { nombre: "Zanahoria", cantidad: 400, unidad: "gr" },
      { nombre: "Cebolla de Huevo Blanca", cantidad: 400, unidad: "gr" },
      { nombre: "Plátano Verde", cantidad: 430, unidad: "gr" },
      { nombre: "Cilantro", cantidad: 200, unidad: "gr" },
      { nombre: "Pasta de Tomate", cantidad: 200, unidad: "gr" },
    ],
  },
  {
    nombre: "Mil Hojas de Papa",
    categoria: "Guarnición",
    porciones_receta: null,
    tiempo_preparacion: "40-45 minutos",
    temperatura_coccion: "180°C",
    rendimiento: null,
    notas: null,
    ingredientes: [
      { nombre: "Papa", cantidad: 1500, unidad: "gr" },
      { nombre: "Cebolla de Huevo Blanca", cantidad: 400, unidad: "gr" },
      { nombre: "Crema de Leche", cantidad: 1000, unidad: "ml" },
      { nombre: "Sal", cantidad: 25, unidad: "gr" },
      { nombre: "Huevo", cantidad: 12, unidad: "und" },
      { nombre: "Albahaca", cantidad: 10, unidad: "gr" },
      { nombre: "Queso Mozzarella", cantidad: 200, unidad: "gr" },
      { nombre: "Queso Parmesano", cantidad: 200, unidad: "gr" },
      { nombre: "Aceite Vegetal", cantidad: 50, unidad: "ml" },
    ],
  },
  {
    nombre: "Orzo al Pesto",
    categoria: "Guarnición",
    porciones_receta: 125,
    tiempo_preparacion: "50 minutos",
    temperatura_coccion: "Fuego alto",
    rendimiento: "4375gr orzo cocido",
    notas: null,
    ingredientes: [
      { nombre: "Orzo", cantidad: 1500, unidad: "gr" },
      { nombre: "Agua", cantidad: 4000, unidad: "ml" },
      { nombre: "Sal", cantidad: 100, unidad: "gr" },
      { nombre: "Aceite Vegetal", cantidad: 180, unidad: "ml" },
      { nombre: "Almendras", cantidad: 250, unidad: "gr" },
      { nombre: "Pesto", cantidad: 1000, unidad: "gr" },
    ],
  },
  // === POSTRE ===
  // (No explicit postre recipes in the 44-dish list from the plan,
  //  but Crepes can serve as postre base. We keep Crepes as Guarnición
  //  per the document categorization.)
];

// ─── MAIN ───
async function main() {
  console.log("🔄 Starting seed process...\n");

  // 1. Insert all unique ingredients
  console.log(`📦 Inserting ${allIngredients.length} ingredients...`);
  const ingredientMap = new Map<string, string>(); // nombre -> id

  for (const ing of allIngredients) {
    const { data, error } = await supabase
      .from("ingredientes_catalogo")
      .insert({
        nombre: ing.nombre,
        unidad: ing.unidad,
        costo_por_unidad: 0,
        proveedor: ing.proveedor,
      })
      .select("id")
      .single();

    if (error) {
      console.error(`  ❌ Error inserting ingredient "${ing.nombre}":`, error.message);
      continue;
    }
    ingredientMap.set(ing.nombre, data.id);
  }
  console.log(`  ✅ Inserted ${ingredientMap.size} ingredients.\n`);

  // 2. Insert all dishes
  console.log(`🍽️  Inserting ${allDishes.length} dishes...`);
  let platoCount = 0;
  let linkCount = 0;

  for (const dish of allDishes) {
    const { data: plato, error: platoErr } = await supabase
      .from("platos_catalogo")
      .insert({
        nombre: dish.nombre,
        precio: 0,
        categoria: dish.categoria,
        tipo_menu: "Menu General",
        porciones_receta: dish.porciones_receta,
        tiempo_preparacion: dish.tiempo_preparacion,
        temperatura_coccion: dish.temperatura_coccion,
        rendimiento: dish.rendimiento,
        notas: dish.notas,
      })
      .select("id")
      .single();

    if (platoErr) {
      console.error(`  ❌ Error inserting dish "${dish.nombre}":`, platoErr.message);
      continue;
    }
    platoCount++;
    const platoId = plato.id;

    // 3. Link ingredients
    const links = dish.ingredientes
      .map((ing) => {
        const ingredienteId = ingredientMap.get(ing.nombre);
        if (!ingredienteId) {
          console.warn(`  ⚠️  Ingredient "${ing.nombre}" not found for dish "${dish.nombre}"`);
          return null;
        }
        return {
          plato_id: platoId,
          ingrediente_id: ingredienteId,
          cantidad: ing.cantidad,
        };
      })
      .filter(Boolean);

    if (links.length > 0) {
      const { error: linkErr } = await supabase
        .from("plato_ingredientes")
        .insert(links as any[]);
      if (linkErr) {
        console.error(`  ❌ Error linking ingredients for "${dish.nombre}":`, linkErr.message);
      } else {
        linkCount += links.length;
      }
    }
  }

  console.log(`  ✅ Inserted ${platoCount} dishes.`);
  console.log(`  ✅ Created ${linkCount} ingredient links.\n`);
  console.log("🎉 Seed complete!");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
